users:
  fdsasd:
    username: fdsasd
    articleIds:
      - 1
    commentIds:
      - 1
  sdf:
    username: sdf
    articleIds: []
    commentIds:
      - 2
articles:
  '1':
    id: 1
    title: test
    url: test
    username: fdsasd
    commentIds:
      - 1
      - 2
    upvotedBy: []
    downvotedBy: []
    comments:
      - &ref_0
        id: 1
        body: test
        username: fdsasd
        articleId: 1
        upvotedBy: []
        downvotedBy: []
nextArticleId: 2
comments:
  '1': *ref_0
  '2':
    id: 2
    body: fds
    username: sdf
    articleId: 1
    upvotedBy: []
    downvotedBy: []
nextCommentId: 3
